server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 118756
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  profiles: test
test:
  config: 123
---
spring:
  profiles: dev
test:
  config: 456